chore: remove Go
aspect-build/rules_jasmine pull request #120
Opened 2024-02-05 20:39 UTC by alexeagle

We don't have any Go sources in rules_jasmine so there's no reason we should install a Go toolchain or worry about upgrading it. 'aspect configure' provides the auto-generation for bzl_library targets so we don't need Gazelle either.

2024-02-05 20:40 UTC, jbedard approved these changes

2024-02-05 21:10 UTC, alexeagle commented
Note, this repo already has a `configure` task on aspect workflows, so we'll continue to have CI coverage to check that `bzl_library` targets are updated.

2024-02-05 21:49 UTC, gregmagolan requested changes
Hold on this until tomorrow to discuss

2024-02-06 06:53 UTC, gregmagolan commented
Keeping gazelle around for rules sets with Workflows CI for gazelle task coverage & as a reference for the task

2024-02-06 06:53 UTC, closed without merging